name: Build

on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
    build:
      continue-on-error: true  
      strategy:
        fail-fast: false
        matrix:
          os: [ ubuntu-latest ]
          app: [ web ]

      name: Building ${{ matrix.app }} on ${{ matrix.os }}
      runs-on: ${{ matrix.os }}
      steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2

      - name: Get dependencies
        run: flutter pub get
      
      - name: Build
        run: flutter build ${{ matrix.app }}
